package com.models;
// Generated 2017-9-7 18:32:58 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments implements java.io.Serializable {

	private Integer comId;
	private User user;
	private String comContent;
	private String comDate;

	public Comments() {
	}

	public Comments(User user, String comContent, String comDate) {
		this.user = user;
		this.comContent = comContent;
		this.comDate = comDate;
	}

	public Integer getComId() {
		return this.comId;
	}

	public void setComId(Integer comId) {
		this.comId = comId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getComContent() {
		return this.comContent;
	}

	public void setComContent(String comContent) {
		this.comContent = comContent;
	}

	public String getComDate() {
		return this.comDate;
	}

	public void setComDate(String comDate) {
		this.comDate = comDate;
	}

}
