package com.models;
// Generated 2017-9-7 18:32:58 by Hibernate Tools 5.2.3.Final

/**
 * Vote generated by hbm2java
 */
public class Vote implements java.io.Serializable {

	private Integer voterId;
	private String VName;
	private String VDept;
	private String VPhone;
	private int VCount;
	private String VPicture;
	private String VVideo;
	private String VProfile;
	public Vote() {
	}

	public Vote(String VName, String VDept, String VPhone, int VCount) {
		this.VName = VName;
		this.VDept = VDept;
		this.VPhone = VPhone;
		this.VCount = VCount;
		
	}

	public Vote(String VName, String VDept, String VPhone, int VCount, String VPicture, String VVideo, String VProfile) {
		this.VName = VName;
		this.VDept = VDept;
		this.VPhone = VPhone;
		this.VCount = VCount;
		this.VPicture = VPicture;
		this.VVideo = VVideo;
		this.VProfile = VProfile;
	}

	public Integer getVoterId() {
		return this.voterId;
	}

	public void setVoterId(Integer voterId) {
		this.voterId = voterId;
	}

	public String getVName() {
		return this.VName;
	}

	public void setVName(String VName) {
		this.VName = VName;
	}

	public String getVDept() {
		return this.VDept;
	}

	public void setVDept(String VDept) {
		this.VDept = VDept;
	}

	public String getVPhone() {
		return this.VPhone;
	}

	public void setVPhone(String VPhone) {
		this.VPhone = VPhone;
	}

	public int getVCount() {
		return this.VCount;
	}

	public void setVCount(int VCount) {
		this.VCount = VCount;
	}

	public String getVPicture() {
		return this.VPicture;
	}

	public void setVPicture(String VPicture) {
		this.VPicture = VPicture;
	}

	public String getVVideo() {
		return this.VVideo;
	}

	public void setVVideo(String VVideo) {
		this.VVideo = VVideo;
	}
	
	public String getVProfile(){
		return this.VProfile;
	}
	
	public void setVProfile(String VProfile){
		this.VProfile = VProfile;
	}

}
